apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
    department: ITService
    priority: High
spec:
  containers:
    - name: nginx-container
      image: nginx:latest